name: Sync Backend to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Backend Subdirectory to HF
        env:
          HF_TOKEN: ${{secrets.HUGGINGFACE_TOKEN}}
        run: |
          #1. Install git-subtree if not present 
          git config --global user.email "github-actions[bot]@://github.com"
          git config --global user.name "github-actions[bot]"

          git subtree split --prefix=backend -b temp-hf-deploy

          git config --local http.https://huggingface.co "Authorization: Bearer $HF_TOKEN"

          git push --force https://HF_USER:$HF_TOKEN@huggingface.co/spaces/UjjwalAgg/Sandeep_Enterprises temp-hf-deploy:main