name: Sync Backend to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Isolate Backend Folder
        run: |
          #1. Install git-subtree if not present 
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git subtree split --prefix=backend -b temp-hf-deploy

      - name: Push to Hugging Face
        uses: mikefarah/lfs-folder-push@v1
        with:
          Repository_url: 'https://huggingface.co'
          branch: 'main'
          folder: 'backend'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          huggingface_token: ${{ secrets.HF_TOKEN }}